### ISSUE TITLE
Mirror rotation should speed up

### ISSUE THREAD

**Issue by BigDomas** [EltonLi2000/IllumiGator#15]
Rotating mirrors a large angle is annoying, as it takes a really long time. However, increasing the speed at which they rotate makes it harder to aim them precisely. The speed at which they rotate should increment over time if the player is holding down the key to allow for fast rotation over large angles, and also fine control over small angles.

**Comment by dakota-cappel** [comment]
I added variables called rotation_factor and increase_speed to the __init__ section of the Character class. When the player gets close enough and interacts with the object, the rotation_factor increases by increase_speed's value every frame (which is because it's in update). Here's the code snippet with the speed calculations and increase of the rotation_factor.

        if self.counter_clockwise and self.closest_interactable and not self.clockwise:
            self.closest_interactable.move(numpy.zeros(2), util.OBJECT_ROTATION_AMOUNT * (2)**self.rotation_factor)
            if self.rotation_factor < 3.00:
                self.rotation_factor = self.rotation_factor + self.increase_rotation

I made a cap at around 3, so the max speed of the rotation is 2^3, or 8 times faster than its base speed.

**Comment by dakota-cappel** [comment]
Forgot to mention, rotation factor gets reset to 0 whenever the Q or E buttons are released. That way the speed resets every time you interact with the rotation of a mirror.
