### ISSUE TITLE
Levels are hard-coded

### ISSUE THREAD

**Issue by BigDomas** [EltonLi2000/IllumiGator#18]
They should be read in from JSON files

**Comment by Pugins** [comment]
Rather than create JSON files directly, it might be better to write a function that creates a JSON using specified coordinates. Then create a functuon that can read level JSON files.

Reason: want to use game constants to create JSON.

Problem: How do users create levels if a function creates the JSON. A solutiom would be to get user input to create the JSON (doesn't need GUI and doesn't even need to necessarily be integrated with game).

This approach would be nice as it allows us to create levels in a flexible manner (important when implement different window sizes). It would also maintain modularity of JSON idea.
